# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-flask-app
spec:
  selector: # Define the wrapping strategy
    matchLabels: # Match all pods with the defined labels
      app: sample-flask-app # Labels follow the `name: value` template
  template: # This is the template of the pod inside the deployment
    metadata:
      labels:
        app: sample-flask-app
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - image: acrbuild2024.azurecr.io/flask-app
          name: sample-flask-app
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 5000
              name: http

---
apiVersion: v1
kind: Service
metadata:
  name: sample-flask-app-service
spec:
  selector:
    app: sample-flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
  type: LoadBalancer

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample-flask-app-ingress
spec:
  rules:
  - host: your-domain.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: sample-flask-app-service
            port:
              number: 80