name: copy-artifact

on:
  workflow_dispatch
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

env:
  BASE_IMAGE_REGISTRY: ${{ vars.BASE_IMAGE_REGISTRY }}
  BASE_IMAGE_REPO: ${{ vars.BASE_IMAGE_REPO }}
  BASE_IMAGE_TAG: ${{ vars.BASE_IMAGE_TAG }}
  TARGET_IMAGE_REGISTRY: ${{ vars.TARGET_IMAGE_REGISTRY }}
  TARGET_IMAGE_REPO: flaskapp
  TARGET_IMAGE_TAG: ${{ vars.TARGET_IMAGE_TAG }}
  # SIGNING_KEY_ID: ${{ vars.SIGNING_KEY_ID }}
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  DOCKERHUB_REGISTRY: ${{ vars.DOCKERHUB_REGISTRY }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  copy-artifact:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Install Go
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.22.5'
      - run: go version
      
      - name: Copy python:3.12.2 to Docker Hub
        uses: truemark/skopeo-copy-action@v1
        with:
          src-image: "docker://library/python:3.12.2"
          dest-image: "${{ vars.DOCKERHUB_REGISTRY }}/python:3.12"
          dest-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dest-password: ${{ secrets.DOCKERHUB_TOKEN }}
          multi-arch: "system"
          
      - name: Checkout SCAI repository  
        uses: actions/checkout@v4  
        with:  
          ref: main  
          repository: in-toto/scai-demos
          
      - name: Install SCAI dependencies  
        run: sudo apt install build-essential
        
      - run: go mod tidy
      - name: Install scai-gen 
        run: make go-mod
        
      - name: Checkout cssc-flaskapp repo
        uses: actions/checkout@v4
        
      - name: Create SCAI attestation
        run: bash ./scai-demo/copy-artifact/copy-artifact.sh
        
      - name: Display attestation file
        run: |
          cat ./scai-demo/copy-artifact/copy-artifact-metadata/copied-artifact.scai.json
          
      - name: Attach attestation file to copied image
        run: oras attach --artifact-type doc/example "${{ vars.DOCKERHUB_REGISTRY }}/python:3.12" ./scai-demo/copy-artifact/copy-artifact-metadata/copied-artifact.scai.json
